services:
  db:
    image: postgres:16-alpine
    container_name: ttc_db_lite
    environment:
      POSTGRES_DB: ttc
      POSTGRES_USER: ttc
      POSTGRES_PASSWORD: ttc
      TZ: America/Toronto
    # No host port exposure; use `docker compose exec` to connect
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./data/processed:/import:ro
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=512m

